### ISSUE TITLE
closeAllConnections() is VERY destructive

### ISSUE THREAD

**Issue by HenrikBengtsson** [EuanMcGonigle/CptNonPar#1]
Hello and congrats to your CRAN release.

As the author of **parallelly**, I'm tracking new packages to see how it's used.  While doing this, I spotted:

https://github.com/EuanMcGonigle/CptNonPar/blob/33b51b10935eb8e5fe437c41138d48f1afee8cff/R/np.mojo.R#L177

Please never ever use `closeAllConnections()` - even less so in an R package.  It is very destructive and it wreaks havoc for the end-user if they have other connections open when they call your function.  This also breaks things like `capture.output()`.  To emphasize this more: It's almost as bad as calling `quit("no")` inside a function.

**Comment by HenrikBengtsson** [comment]
I should probably also say that the fix is simple; just drop `closeAllConnections()` - it's not needed

**Comment by EuanMcGonigle** [comment]
Thanks for bringing this to my attention! This has been corrected in the development version on Github that will be sent to CRAN in the next month.

**Comment by HenrikBengtsson** [comment]
Excellent. Thanks.
